name: Jobs Test 5

"on":
  push:
    branches: [master, main, develop]

jobs:
  container-scan:
    name: "Container · Trivy Image Scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        if: hashFiles('Dockerfile') != ''
        run: echo test
