name: Jobs Test 4

"on":
  push:
    branches: [master, main, develop]

jobs:
  container-scan:
    name: "Container · Trivy Image Scan"
    runs-on: ubuntu-latest
    if: hashFiles('Dockerfile') != ''
    steps:
      - run: echo test
